Fix build from scratch
Summary:

While trying to build this from scratch I saw the following error:

```
kuduraft/src/kudu/tools/tool_action_common.cc:62:10: fatal error: kudu/tserver/tserver_admin.proxy.h: No such file or directory
 #include "kudu/tserver/tserver_admin.proxy.h"   // IWYU pragma: keep
```

This is because at some point we included `tserver_admin_proxy` in
`tool_action_common.cc` but did not list `tserver` as a dependency for the
`kudu_tools_util` target. Include it here

Test Plan:

```
cd build
cmake ..
make
```

Make sure build succeeds.

Reviewers: anirbanr-fb, bhatvinay, mpercy, li-chi

Subscribers:

Tasks:

Tags:
Signed-off-by: Yichen <yichenshen@fb.com>